### ISSUE TITLE
'Set Time' Not Functioning Correctly

### ISSUE THREAD

**Issue by BlockedBlock** [DeveloperMaris/Time#11]
On the 'Set time' section, what is supposed to be the 24 hour clock on the bottom is instead another 12 hour clock, meaning both the top clock and the bottom clock just mirror each other. The app used to function correctly but seemed to stopped functioning after I updated my iPhone to iOS 16.5
![IMG_5916](https://github.com/DeveloperMaris/Time/assets/89721331/3d855147-00fd-4bfb-8357-afc7c515f3f6)

**Comment by DeveloperMaris** [comment]
Thank you for reporting this issue, it will be fixed in the upcoming release.
